# Generated by Django 5.2.3 on 2025-08-16 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a00_accounts', '0001_initial'),
        ('a10_topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='common_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a10_topics.projectmachines'),
        ),
    ]
