# Generated by Django 5.2.3 on 2025-08-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a00_accounts', '0002_cooperation_common_project'),
        ('a10_topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperation',
            old_name='users',
            new_name='connections',
        ),
        migrations.RenameField(
            model_name='cooperation',
            old_name='connection_type',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='common_project',
        ),
        migrations.AddField(
            model_name='cooperation',
            name='rojects',
            field=models.ManyToManyField(to='a10_topics.projectmachines'),
        ),
    ]
