# Generated by Django 5.2.3 on 2025-08-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a00_accounts', '0003_rename_users_cooperation_connections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperation',
            old_name='rojects',
            new_name='projects',
        ),
        migrations.RenameField(
            model_name='cooperation',
            old_name='connections',
            new_name='users',
        ),
    ]
