# Generated by Django 5.2.3 on 2025-08-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netzplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMachines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=16, null=True)),
                ('machine', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vorgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetzplanVorgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, null=True)),
                ('netzplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a10_topics.netzplan')),
                ('vorgang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a10_topics.vorgang')),
            ],
        ),
    ]
