# Generated by Django 5.2.3 on 2025-08-15 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a11_informations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekSelected', models.DateField(null=True)),
                ('monthSelected', models.DateField(null=True)),
                ('rangeStart', models.DateField(null=True)),
                ('rangeEnd', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersWorkTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('travel_start', models.TimeField(null=True)),
                ('travel_end', models.TimeField(null=True)),
                ('work_start', models.TimeField(null=True)),
                ('work_end', models.TimeField(null=True)),
                ('project_machine', models.CharField(max_length=32, null=True)),
                ('netzplan_vorgang', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workimes_standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a11_informations.worktimesstandard')),
            ],
            options={
                'db_table': 'a20_users_worktimes',
            },
        ),
    ]
