# Generated by Django 5.2.3 on 2025-08-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a20_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersworktimes',
            table=None,
        ),
    ]
