# Generated by Django 5.2.3 on 2025-08-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a20_users', '0002_alter_usersworktimes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersworktimes',
            table='a20_users_usersworktimes',
        ),
    ]
