# Generated by Django 5.2.3 on 2025-08-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailReciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=16)),
                ('lastName', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimesStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=16, null=True)),
                ('workTime', models.TimeField()),
                ('breakTime', models.TimeField()),
            ],
        ),
    ]
