# Generated by Django 5.2.3 on 2025-08-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a11_informations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Countries_ISO3166",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                ("stateName", models.CharField(max_length=32)),
                ("A_2", models.CharField(max_length=2, unique=True)),
                ("A_3", models.CharField(max_length=3, unique=True)),
                ("num", models.CharField(max_length=3, unique=True)),
                (
                    "sovereign",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a11_informations.countries_iso3166",
                    ),
                ),
            ],
        ),
    ]
